# Generated by Django 4.2.4 on 2024-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_image',
            field=models.ImageField(null=True, upload_to='subject_images/'),
        ),
    ]
